#!/usr/bin/env python3
"""Generates m17n/uz-Mulga.mim.

Worth generating rather than hand-writing because fcitx5-m17n names an incoming
key in three different ways, and a rule has to exist for each name a given
character might arrive under:

  * printable ASCII      the literal character   (engine.cpp KeySymToSymbol)
  * a named X keysym     that keysym's name      ("acute", "rightsinglequotemark")
  * anything else        "U+XXXX"                (keysymname.cpp KeySymName)

Which one turns up depends on the keyboard layout, so both the named and the
U+ forms are emitted wherever a name exists. Note that raw keysyms 0x02BB and
0x02BC are the Latin-3 letters ğ and ĵ, nothing to do with the modifier
letters, so the U+ form is the only way to name those.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "m17n" / "uz-Mulga.mim"

# The tutuq belgisi, in every shape a keyboard might send it.
# character, description, X keysym name if one exists
APOSTROPHES = [
    ("'", "U+0027 APOSTROPHE", "apostrophe"),
    ("`", "U+0060 GRAVE ACCENT", "grave"),
    ("´", "U+00B4 ACUTE ACCENT", "acute"),
    ("ʹ", "U+02B9 MODIFIER LETTER PRIME", None),
    ("ʻ", "U+02BB MODIFIER LETTER TURNED COMMA", None),
    ("ʼ", "U+02BC MODIFIER LETTER APOSTROPHE", None),
    ("‘", "U+2018 LEFT SINGLE QUOTATION MARK", "leftsinglequotemark"),
    ("’", "U+2019 RIGHT SINGLE QUOTATION MARK", "rightsinglequotemark"),
    ("′", "U+2032 PRIME", "minutes"),
]

DIGRAPHS = [("s", "S", "ş", "Ş"), ("c", "C", "ç", "Ç")]
APOS_LETTERS = [("o", "O", "ö", "Ö"), ("g", "G", "ǧ", "Ǧ")]


def key_names(ch):
    """Every m17n key name this character could arrive under."""
    if " " <= ch <= "~":
        return [None]          # a literal in a string is enough
    names = ["U+%04X" % ord(ch)]
    for _c, _d, keysym in APOSTROPHES:
        if _c == ch and keysym:
            names.append(keysym)
    return names


def main():
    L = []
    w = L.append
    w(";; uz-Mulga.mim : the reformed Uzbek Latin alphabet")
    w(";;")
    w(";;   sh -> ş    ch -> ç    o' -> ö    g' -> ǧ")
    w(";;")
    w(";; Built like latn-post.mim: a plain sequence table. m17n holds a key")
    w(";; only for as long as it is the prefix of some rule, so `s` followed by")
    w(";; anything other than `h` commits a plain `s`, and the apostrophe in")
    w(";; `as'hob` releases the `s` so the `h` after it stays a letter of its")
    w(";; own.")
    w(";;")
    w(";; Generated by tools/gen_mim.py. Do not edit by hand.")
    w(";; Install by copying to ~/.m17n.d/ : no compilation, no root.")
    w("")
    w("(input-method uz Mulga)")
    w("")
    w('(description "Reformed Uzbek Latin alphabet. Type sh, ch, o\' or g\' '
      'and it folds into ş, ç, ö or ǧ.")')
    w("")
    w('(title "UZ")')
    w("")
    w("(map")
    w(" (trans")
    w("  ;; sh and ch. `sH` and `cH` are deliberately missing: a lowercase")
    w("  ;; letter followed by a capital H is not a word anyone types on")
    w("  ;; purpose, so it stays two letters.")
    for low, up, out_low, out_up in DIGRAPHS:
        w('  ("%sh" "%s") ("%sh" "%s") ("%sH" "%s")'
          % (low, out_low, up, out_up, up, out_up))
    w("")
    w("  ;; o' and g'. One row per shape the tutuq belgisi can arrive as, and")
    w("  ;; per name fcitx5-m17n might give it.")
    for ch, desc, _keysym in APOSTROPHES:
        for names in [key_names(ch)]:
            for name in names:
                cells = []
                for low, up, out_low, out_up in APOS_LETTERS:
                    for letter, out in ((low, out_low), (up, out_up)):
                        if name is None:
                            cells.append('("%s%s" "%s")' % (letter, ch, out))
                        else:
                            cells.append('((?%s %s) "%s")' % (letter, name, out))
                w("  " + " ".join(cells) + "   ; " + desc
                  + ("" if name is None else " as %s" % name))
    w("")
    w("  ;; Doubling escape, for borrowings that want a literal sh or ch. Left")
    w("  ;; off on purpose so this file behaves exactly like the fcitx5 addon;")
    w("  ;; turning it on is not free, because `sh` and `ch` become prefixes of")
    w("  ;; a longer rule and stop committing until the following key arrives.")
    w('  ;;   ("shh" "sh") ("Shh" "Sh") ("SHH" "SH")')
    w('  ;;   ("chh" "ch") ("Chh" "Ch") ("CHH" "CH")')
    w("  ))")
    w("")
    w("(state")
    w(" (init")
    w("  (trans)))")
    w("")
    w(";; Local Variables:")
    w(";; mode: lisp")
    w(";; End:")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    rules = sum(l.count('") (') + 1 for l in L
                if l.strip().startswith(('("', '((')))
    print("wrote %s (%d rules)" % (OUT.relative_to(ROOT), rules))


if __name__ == "__main__":
    main()
